name: flutter_application_1
description: "A new Flutter project."

publish_to: 'none' # Prevents accidental publishing to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  # The following line ensures that the Material Icons font is included with your application
  uses-material-design: true

  # Add assets to your application here
  assets:
    - assets/profile_picture.png.jpg

